version: 1
disable_existing_loggers: true

formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  request:
    format: "%(asctime)s - %(name)s - %(message)s"
  error:
    format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

filters:
    infoFilter:
        (): utils.filters.info_filter
    errorFilter:
        (): utils.filters.error_filter
    debugFilter:
        (): utils.filters.debug_filter
    traceFilter:
        (): utils.filters.trace_filter
        
        
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: ./Logs/info.log
    maxBytes: 16777216 # 16MB
    backupCount: 5
    filters: [infoFilter]
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: standard
    filename: ./Logs/errors.log
    maxBytes: 16777216 # 16MB
    backupCount: 5
    filters: [errorFilter]
    encoding: utf8

  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: ./Logs/debug.log
    maxBytes: 16777216 # 16MB
    backupCount: 5
    filters: [debugFilter]
    encoding: utf8
    
  trace_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: 9
    formatter: request
    filename: ./Logs/trace.log
    maxBytes: 16777216 # 16MB
    backupCount: 5
    filters: [traceFilter]
    encoding: utf8

loggers:
  simpleExample:
    level: 9
    handlers: [info_file_handler, error_file_handler, debug_file_handler,trace_file_handler]
    propagate: no

root:
  level: 9
  handlers: [info_file_handler, error_file_handler, debug_file_handler,trace_file_handler]